### PR TITLE
Interpretation using Tree Surrogates

### PR DESCRIPTION
**Pull request by pramitchoudhary**
This idea of explaining model's learned decision policies by extracting rules using a tree based surrogate model is influenced by the work of Mark W. Craven captured as the Trepan algorithm. 
This PR implements functions to extract the rules as "if else then" hierarchical conditional statements. The results could be visualized or rendered as text both for global and local interpretation.

Reference papers:
1. http://ftp.cs.wisc.edu/machine-learning/shavlik-group/craven.thesis.pdf
2. Extracting Tree structured Representations of Trained Networks: https://papers.nips.cc/paper/1152-extracting-tree-structured-representations-of-trained-networks.pdf

### CODE REVIEW

**Comment by pramitchoudhary** [comment]
thanks, @silversurfer84. As you make changes, it would be great if you could help review the code as well

**Comment by pramitchoudhary** [comment]
@silversurfer84 the changes looks good to me. There are more improvements that we can plan but for let's merge the changes to master(_if the build passes without any issues_). And then pick it up from there. Thanks for helping out with the PR. I can help with the merge.

**Comment by silversurfer84** [comment]
@pramitchoudhary initial changes for supporting rule based explanation using tree surrogates should be good for merging to master. Let me know, if there are some immediate considerations to be considered.

**Comment by pramitchoudhary** [comment]
@silversurfer84 just saw the changes. Looks good to me. Merging this version for now. Further improvements could be considered as a follow-up.

**Pull request merged**
