### PR TITLE
Issue 161

### PR DESCRIPTION
**Pull request by aikramer2**

### CODE REVIEW

**Comment by aikramer2** [comment]
This is actually for issue 154, multiprocessing feature importance.
https://github.com/datascienceinc/Skater/issues/154

**Comment by aikramer2** [comment]
i just tried this change on the boston dataset with a regression. compute time **increased** from 57 ms to 131 ms. On a RF with lending club data (30 K rows, 80 features), the compute time **decreased** from 39 seconds to 15 seconds

**Comment by pramitchoudhary** [comment]
Is this pull request, still valid ? @aikramer2

**Comment by aikramer2** [comment]
@pramitchoudhary assuming this CI builds, Im going to merge this, despite the fact that for very very small models/datasets, multiple jobs overhead increases run time. Its neglible.

**Pull request merged**
